### PR TITLE
Added everysk testimonial and removed placeholder RMJ testimonial

### PR DESCRIPTION
**Pull request by ericmjl**
Explicitly asking for @twiecki's review here. Please check out the deploy preview to make sure it looks professional and up-to-snuff. 

As we collect more testimonials, I've got a few ideas for adding UI elements to the website to so that it doesn't become a long laundry list :smile:. They will be added as it becomes necessary. (Let's not over-optimize early on.)

### CODE REVIEW

**Comment by lucianopaz** [comment]
This looks great @ericmjl! Can we somehow add the company's logo along with its name?

**Comment by canyon289** [comment]
Before we do this, did we explicitly get permission to use their logo? 

From a website perspective though it would be awesome if the site was designed to incorporate logos for the clients that do approve!

**Comment by twiecki** [comment]
Yes.

**Comment by ericmjl** [comment]
okie dokes guys, gonna hack on the website tonight to factor in logos :)

**Review by twiecki — APPROVED** [review]

**Pull request merged**
