### PR TITLE
Migrate testimonials page to clients page

### LINKED ISSUE #20: Testimonials should just be "clients"
We won't have testimonials from all clients, so maybe just have the logos there and then maybe have testimonials in a separate section below that.

### PR DESCRIPTION
**Pull request by ericmjl**
Closes #20.

This was a bit harder than I had originally anticipated, but managed to get it to work.

I have used [Card Columns](https://getbootstrap.com/docs/4.0/components/card/#card-columns) as the layout format. Gives us a Pintrest-like view over clients. If testimonial is provided, they are shown, otherwise just logos.

Logos have a 10 px border around them added in programmatically by CSS. This helps; previously, the logos were touching the card borders directly.

### CODE REVIEW

**Review by OriolAbril — APPROVED** [review]
Looks good, only nit is I would make the logos clickable if possible.

**Comment by ericmjl** [comment]
@OriolAbril ok, no problemo!

**Comment by twiecki** [comment]
Very cool, thanks for the quick turn-around!

**Comment by ericmjl** [comment]
Yes, that's right, it's changed to `/clients`.

**Comment by ericmjl** [comment]
Though I'm noticing that the Akiri logo is down.

**Comment by twiecki** [comment]
maybe because of the name which is akilii not akili.

**Pull request merged**
