### PR TITLE
SEMBR

### PR DESCRIPTION
**Pull request by ericmjl**
Applied semantic line breaks (SEMBR). This makes prose easier to maintain and diff in the long-run.

For more info on SEMBR: https://sembr.org.

### CODE REVIEW

**Review by canyon289 — COMMENTED** [review]
I dont have a strong feeling on this one way or another. Do love how rapidly were progressing on the website

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Thanks @ericmjl!

**Comment by twiecki** [comment]
No VS plugin? :(

**Comment by ericmjl** [comment]
lol, haha, nonononono, just "no vscode config files" allowed.

**Comment by twiecki** [comment]
No I meant there is no plugin to apply SEMBR.

**Comment by ericmjl** [comment]
Ohhh haha. Yeah, there's none. It's tough, because semantics are both context-specific and human-directed (double-whammy against automation).

**Comment by twiecki** [comment]
Oh you did that by hand?

**Comment by ericmjl** [comment]
Yeah. It's easy though, and doing this is an exercise in reading through the entire doc anyways :)

**Pull request merged**
